language: node_js

node_js:
  - "10.16.3"

cache:
  directories:
    - node_modules

script:
  - npm run test

install:
  - npm install

before_deploy:
  # That's not obvious here, but environment variables are used during this build,
  # like REACT_APP_SERVER_ROOL_URL, to get the environment right when generating static files.
  # These environment variables are configured on Travis-CI website (project settings).
  - npm run build
  # The CNAME file is used by surge.sh to automatically detect under which domain name
  # the project should be deployed.
  - cp $TRAVIS_BUILD_DIR/CNAME $TRAVIS_BUILD_DIR/build/
  # Ensure that the client will always reach the router on surge.sh by adding a 200.html file.
  # Used when the user tries to directly access a specific URL different than the root one.
  # See https://surge.sh/help/adding-a-200-page-for-client-side-routing for more information.
  - cp $TRAVIS_BUILD_DIR/build/index.html $TRAVIS_BUILD_DIR/build/200.html

deploy:
  provider: surge
  on: master
  # This `skip_cleanup` is important, as it prevents Travis-CI to cleanup the files
  # generated in the `build` folder by the `before_deploy:` section above...
  skip_cleanup: true
  # ...which can then be deployed to surge.sh from this `build` folder.
  project: ./build/
